/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Varibles } from "./Varibles";
export * as factories from "./factories";
export { Varibles__factory } from "./factories/Varibles__factory";
