/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Function } from "./Function";
export * as factories from "./factories";
export { Function__factory } from "./factories/Function__factory";
