/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Integers } from "./Integers";
export * as factories from "./factories";
export { Integers__factory } from "./factories/Integers__factory";
