/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface ArraysInterface extends utils.Interface {
  functions: {
    "defineArray()": FunctionFragment;
    "defineName()": FunctionFragment;
    "getNames()": FunctionFragment;
    "getarray()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "defineArray"
      | "defineName"
      | "getNames"
      | "getarray"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "defineArray",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "defineName",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getNames", values?: undefined): string;
  encodeFunctionData(functionFragment: "getarray", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "defineArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "defineName", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getNames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getarray", data: BytesLike): Result;

  events: {};
}

export interface Arrays extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ArraysInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    defineArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    defineName(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getNames(overrides?: CallOverrides): Promise<[string[]]>;

    getarray(overrides?: CallOverrides): Promise<[[BigNumber, BigNumber]]>;
  };

  defineArray(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  defineName(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getNames(overrides?: CallOverrides): Promise<string[]>;

  getarray(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;

  callStatic: {
    defineArray(overrides?: CallOverrides): Promise<void>;

    defineName(overrides?: CallOverrides): Promise<void>;

    getNames(overrides?: CallOverrides): Promise<string[]>;

    getarray(overrides?: CallOverrides): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    defineArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    defineName(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getNames(overrides?: CallOverrides): Promise<BigNumber>;

    getarray(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    defineArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    defineName(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getNames(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getarray(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
