/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Arrays } from "./Arrays";
export * as factories from "./factories";
export { Arrays__factory } from "./factories/Arrays__factory";
